WITH fct_orders AS (
  SELECT
    *
  FROM {{ ref('fct_orders') }}
), filter_1 AS (
  SELECT
    *
  FROM fct_orders
  WHERE
    ORDER_DATE >= '1995-01-01' AND NET_REVENUE_USD > 0 AND IS_FULFILLED = TRUE
), rename_1 AS (
  SELECT
    ID_ORDER AS ORDER_ID,
    ID_CUSTOMER AS CUSTOMER_ID,
    ORDER_DATE,
    LINES_COUNT AS ORDER_LINES_COUNT,
    GROSS_REVENUE_USD AS GROSS_REV_USD,
    DISCOUNT_AMOUNT_USD AS DISCOUNT_USD,
    TAX_AMOUNT_USD AS TAX_USD,
    NET_REVENUE_USD AS NET_REV_USD,
    ORDER_PRIORITY,
    ORDER_CLERK,
    SHIP_PRIORITY_RANK,
    ORDER_STATUS,
    IS_FULFILLED,
    STAGED_AT_UTC
  FROM filter_1
), test_sql AS (
  SELECT
    *
  FROM rename_1
)
SELECT
  *
FROM test_sql